# Generated by Django 5.0.1 on 2024-02-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogBack", "0004_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("draft", "Draft")],
                default="active",
                max_length=10,
            ),
        ),
    ]
