# Generated by Django 5.0.1 on 2024-02-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogBack", "0005_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
